/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package liberaryproject.EditData;

import liberaryproject.Menu.ManageBooks;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rozi Roti
 */
public class EditBookInfo extends javax.swing.JFrame {

    /**
     * Creates new form EditBookInfo
     */
    public EditBookInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        indiraPannel = new javax.swing.JPanel();
        indiraButton = new javax.swing.JButton();
        primaryPsnnel = new javax.swing.JPanel();
        accessionNumberLabel = new javax.swing.JLabel();
        accessionNumberField = new javax.swing.JTextField();
        classNumberLabel = new javax.swing.JLabel();
        classNumberField = new javax.swing.JTextField();
        detailPannel = new javax.swing.JPanel();
        bookTitleField = new javax.swing.JTextField();
        authorNameField = new javax.swing.JTextField();
        editionField = new javax.swing.JTextField();
        bookTitleLabel = new javax.swing.JLabel();
        authorNameLabel = new javax.swing.JLabel();
        editionLabel = new javax.swing.JLabel();
        addressPannel = new javax.swing.JPanel();
        countLabel = new javax.swing.JLabel();
        rowLabel = new javax.swing.JLabel();
        columnLabel = new javax.swing.JLabel();
        countField = new javax.swing.JTextField();
        rowNumberfield = new javax.swing.JTextField();
        columnNumberfield = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        searchidTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        indiraPannel.setBackground(new java.awt.Color(18, 49, 113));

        indiraButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        indiraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indiraButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout indiraPannelLayout = new javax.swing.GroupLayout(indiraPannel);
        indiraPannel.setLayout(indiraPannelLayout);
        indiraPannelLayout.setHorizontalGroup(
            indiraPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indiraPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(indiraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        indiraPannelLayout.setVerticalGroup(
            indiraPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, indiraPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(indiraButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        primaryPsnnel.setBackground(new java.awt.Color(153, 255, 153));
        primaryPsnnel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        accessionNumberLabel.setText("Accession no.:");

        classNumberLabel.setText("Class No.:");

        javax.swing.GroupLayout primaryPsnnelLayout = new javax.swing.GroupLayout(primaryPsnnel);
        primaryPsnnel.setLayout(primaryPsnnelLayout);
        primaryPsnnelLayout.setHorizontalGroup(
            primaryPsnnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(primaryPsnnelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(primaryPsnnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accessionNumberLabel)
                    .addComponent(classNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(primaryPsnnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accessionNumberField))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        primaryPsnnelLayout.setVerticalGroup(
            primaryPsnnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(primaryPsnnelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(primaryPsnnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accessionNumberLabel)
                    .addComponent(accessionNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(primaryPsnnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classNumberLabel)
                    .addComponent(classNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        detailPannel.setBackground(new java.awt.Color(153, 255, 153));
        detailPannel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bookTitleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTitleFieldActionPerformed(evt);
            }
        });

        bookTitleLabel.setText("Book Title:");

        authorNameLabel.setText("Author Name:");

        editionLabel.setText("Edition:");
        editionLabel.setToolTipText("");

        javax.swing.GroupLayout detailPannelLayout = new javax.swing.GroupLayout(detailPannel);
        detailPannel.setLayout(detailPannelLayout);
        detailPannelLayout.setHorizontalGroup(
            detailPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookTitleLabel)
                    .addComponent(authorNameLabel)
                    .addComponent(editionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(detailPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(authorNameField)
                    .addComponent(editionField)
                    .addComponent(bookTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        detailPannelLayout.setVerticalGroup(
            detailPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPannelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(detailPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookTitleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editionLabel))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        addressPannel.setBackground(new java.awt.Color(153, 255, 153));
        addressPannel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        countLabel.setText("Count:");

        rowLabel.setText("Row No.:");

        columnLabel.setText("Column No.:");

        rowNumberfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rowNumberfieldActionPerformed(evt);
            }
        });

        columnNumberfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columnNumberfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addressPannelLayout = new javax.swing.GroupLayout(addressPannel);
        addressPannel.setLayout(addressPannelLayout);
        addressPannelLayout.setHorizontalGroup(
            addressPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addressPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(countLabel)
                    .addComponent(rowLabel)
                    .addComponent(columnLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addressPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addressPannelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(columnNumberfield))
                    .addComponent(countField)
                    .addComponent(rowNumberfield, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        addressPannelLayout.setVerticalGroup(
            addressPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressPannelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(addressPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addressPannelLayout.createSequentialGroup()
                        .addComponent(countField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rowNumberfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addressPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(columnNumberfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(columnLabel)))
                    .addGroup(addressPannelLayout.createSequentialGroup()
                        .addComponent(countLabel)
                        .addGap(18, 18, 18)
                        .addComponent(rowLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        titleLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titleLabel.setText("Edit Book");

        updateButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Checkmark_25px_1.png"))); // NOI18N
        updateButton.setText("Update");
        updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateButtonMouseClicked(evt);
            }
        });
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Back_25px.png"))); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Accession No.:");

        searchidTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchidTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchidTextFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indiraPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(299, 299, 299)
                        .addComponent(updateButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(primaryPsnnel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(detailPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addComponent(addressPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(indiraPannel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchidTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(detailPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(primaryPsnnel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addressPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(updateButton)
                        .addGap(21, 21, 21))
                    .addComponent(backButton, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void indiraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indiraButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_indiraButtonActionPerformed

    private void bookTitleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTitleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookTitleFieldActionPerformed

    private void rowNumberfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rowNumberfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rowNumberfieldActionPerformed

    private void columnNumberfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columnNumberfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_columnNumberfieldActionPerformed

    private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseClicked
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
            con = DriverManager.getConnection("jdbc:mysql://localhost/liberaryproject","root", "");
            System.out.print("Database is connected !");
            Statement stmt=con.createStatement();
            String ano=accessionNumberField.getText();
            String cno=classNumberField.getText();
            String bname=bookTitleField.getText();
            String aname=authorNameField.getText();
            String edition=editionField.getText();
            String count=countField.getText();
            String row=rowNumberfield.getText();
            String column=columnNumberfield.getText();
            PreparedStatement ps = con.prepareStatement("update books  set `Accession No`=?,`Class No`=?,`Book Title=?,``Author Name`=?,`Edition`=?,`Count`=?,`Row No`=?,`Column No`=? where `Accession No`=? ");
            ps.setString(1, ano);
            ps.setString(2, cno);
            ps.setString(3, bname);
            ps.setString(4, aname);
            ps.setString(5, edition);
            ps.setString(6, count);
            ps.setString(7, row);
            ps.setString(8, column);
            ps.setString(9, ano);
            ps.executeUpdate();
           
            con.close();
            JOptionPane.showMessageDialog(null, "Book Updated");
            
        }
        catch(  ClassNotFoundException | SQLException e)
        {
            System.out.print("Do not connect to DB - Error:"+e);
        }
        accessionNumberField.setText("");
        classNumberField.setText("");
        bookTitleField.setText("");
        authorNameField.setText("");
        editionField.setText("");
        countField.setText("");
        rowNumberfield.setText("");
        columnNumberfield.setText("");

    }//GEN-LAST:event_updateButtonMouseClicked

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        ManageBooks manageBooks=new ManageBooks();
        manageBooks.setVisible(true);

        //To close the current window
        EditBookInfo editbookinfo= new EditBookInfo();
        editbookinfo.setVisible(false);
        dispose();

    }//GEN-LAST:event_backButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonActionPerformed

    private void searchidTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchidTextFieldKeyTyped
        // TODO add your handling code here:
        String no=searchidTextField.getText();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
            con = DriverManager.getConnection("jdbc:mysql://localhost/liberaryproject","root", "");
            System.out.print("Database is connected!!");
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from books where `Accession No`=no");
            while(rs.next()){
                //Retrieve by column name
                 String ano = rs.getString("Accession No");
                 String cno = rs.getString("Class No");
                 String booktitle = rs.getString("Book Title");
                 String aname = rs.getString("Author Name");
                 String edition = rs.getString("Edition");
                 String count = rs.getString("Count");
                 String rowno= rs.getString("Row No");
                 String columnno = rs.getString("Column No");
                 System.out.println("Accession No : " + ano);
                 System.out.println("Class No : " + cno);
                 System.out.println("Book Title : " + booktitle);
                 System.out.println("Author Name : " + aname);
                 System.out.println("Edition : " + edition);
                 System.out.println("Count : " + count);
                 System.out.println("Row No : " + rowno);
                 System.out.println("Column No : " + columnno);
                                  //Display values
                 accessionNumberField.setText(ano);
                 classNumberField.setText(cno);
                 bookTitleField.setText(booktitle);
                 authorNameField.setText(aname);
                 editionField.setText(edition);
                 countField.setText(count);
                 rowNumberfield.setText(rowno);
                 columnNumberfield.setText(columnno);
      }
      rs.close();
            con.close();
            
        }
        catch(  ClassNotFoundException | SQLException e)
        {
            System.out.print("Do not connect to DB - Error:"+e);
        }
    }//GEN-LAST:event_searchidTextFieldKeyTyped

    private void searchidTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchidTextFieldKeyPressed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
            con = DriverManager.getConnection("jdbc:mysql://localhost/liberaryproject","root", "");
            System.out.print("Database is connected!!");
            String selectSQL = "select * from books where `Accessionno`=?";
            PreparedStatement ps = con.prepareStatement(selectSQL);
            ps.setString(1, searchidTextField.getText());
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                //Retrieve by column name
                 String ano = rs.getString(1);
                 String cno = rs.getString(2);
                 String booktitle = rs.getString(3);
                 String aname = rs.getString(4);
                 String edition = rs.getString(5);
                 String count = rs.getString(6);
                 String rowno= rs.getString(7);
                 String columnno = rs.getString(8);
                 System.out.println("Accession No : " + ano);
                 System.out.println("Class No : " + cno);
                 System.out.println("Book Title : " + booktitle);
                 System.out.println("Author Name : " + aname);
                 System.out.println("Edition : " + edition);
                 System.out.println("Count : " + count);
                 System.out.println("Row No : " + rowno);
                 System.out.println("Column No : " + columnno);
                                  //Display values
                 accessionNumberField.setText(ano);
                 classNumberField.setText(cno);
                 bookTitleField.setText(booktitle);
                 authorNameField.setText(aname);
                 editionField.setText(edition);
                 countField.setText(count);
                 rowNumberfield.setText(rowno);
                 columnNumberfield.setText(columnno);
                 JOptionPane.showMessageDialog(null, "Book Updated");
                }
                rs.close();
         con.close();
            
        }
        catch(  ClassNotFoundException | SQLException e)
        {
            System.out.print("Do not connect to DB - Error:"+e);
        }
    }//GEN-LAST:event_searchidTextFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditBookInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditBookInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditBookInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditBookInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditBookInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accessionNumberField;
    private javax.swing.JLabel accessionNumberLabel;
    private javax.swing.JPanel addressPannel;
    private javax.swing.JTextField authorNameField;
    private javax.swing.JLabel authorNameLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField bookTitleField;
    private javax.swing.JLabel bookTitleLabel;
    private javax.swing.JTextField classNumberField;
    private javax.swing.JLabel classNumberLabel;
    private javax.swing.JLabel columnLabel;
    private javax.swing.JTextField columnNumberfield;
    private javax.swing.JTextField countField;
    private javax.swing.JLabel countLabel;
    private javax.swing.JPanel detailPannel;
    private javax.swing.JTextField editionField;
    private javax.swing.JLabel editionLabel;
    private javax.swing.JButton indiraButton;
    private javax.swing.JPanel indiraPannel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel primaryPsnnel;
    private javax.swing.JLabel rowLabel;
    private javax.swing.JTextField rowNumberfield;
    private javax.swing.JTextField searchidTextField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
